program: experiment.py
metric:
  name: accuracy
  goal: maximize
method: bayes
parameters:
  data.imagenet_sketch.labelling.kind:
    values:
      - simple
      - synset
  coop.n_ctx:
    values:
      - 1
      - 8
      - 16
      - 32
  train.lr:
    max: 0.01
    min: 0.0001
