base_model: NousResearch/Llama-2-7b-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

hub_model_id: bdsaglam/llama-2-7b-hf-kg-cons-axolotl

load_in_8bit: true
load_in_4bit: false
strict: false

datasets:
  - path: bdsaglam/web_nlg-erx-instruction-alpaca-debug
    type: alpaca
dataset_prepared_path:
val_set_size: 0

output_dir: ./llama-2-7b-hf-kg-cons-axolotl

adapter: lora
lora_model_dir:

sequence_len: 600
sample_packing: false
pad_to_sequence_len: true

lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

local_rank:

bf16: false
fp16: false
tf32: false
early_stopping_patience:
gradient_accumulation_steps: 1
gradient_checkpointing: false
group_by_length: true
learning_rate: 0.0002
logging_steps: 25
lr_scheduler: cosine
micro_batch_size: 4
num_epochs: 1
optimizer: adamw_bnb_8bit
train_on_inputs: false
warmup_steps: 10
weight_decay: 0.001
resume_from_checkpoint:

xformers_attention:
flash_attention: false

eval_steps: 
eval_table_size:
eval_table_max_new_tokens: 256

save_steps:

deepspeed:
fsdp:
fsdp_config:

debug:

wandb_project: thesis-kgcons
wandb_entity: bdsaglam
wandb_watch:
wandb_run_id:
wandb_log_model: false