seed: 42

base_model: meta-llama/llama-2-7b-chat-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

output_dir: ./llama-2-7b-chat-hf-kg-cons-axolotl
hub_model_id: bdsaglam/llama-2-7b-chat-hf-kg-cons-axolotl

special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

datasets:
  - path: bdsaglam/web_nlg-erx-sft-sharegpt
    type: sharegpt
    conversation: llama-2
val_set_size: 0

load_in_8bit: false
load_in_4bit: true
bf16: false
fp16: true
float16: true

adapter: lora
lora_alpha: 16
lora_dropout: 0.1
lora_r: 64
lora_target_modules:
lora_target_linear: true
lora_model_dir:

flash_attention: true

sequence_len: 600
pad_to_sequence_len: true
sample_packing: false
group_by_length: true
train_on_inputs: false

num_epochs: 1
micro_batch_size: 2
gradient_accumulation_steps: 4
max_grad_norm: 0.3
weight_decay: 0.001
learning_rate: 0.0002
optimizer: paged_adamw_32bit
lr_scheduler: cosine
warmup_steps: 10
logging_steps: 25
save_steps:
eval_steps: 
eval_table_size:
eval_table_max_new_tokens: 180
resume_from_checkpoint:

wandb_project: thesis-kgcons
wandb_entity: bdsaglam
wandb_mode: online
wandb_log_model: end
wandb_run_id:
wandb_watch:

debug:
strict: false

# Don't mess with this, it's here for accelerate and torchrun
local_rank: