model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo-1106
    litellm_params:
      model: gpt-3.5-turbo-1106
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4-0613
    litellm_params:
      model: gpt-4-0613
      api_key: os.environ/OPENAI_API_KEY
  - model_name: text-embedding-ada-002
    litellm_params:
      model: text-embedding-ada-002
      api_key: os.environ/OPENAI_API_KEY
  - model_name: llama-2-7b-chat-jerx
    litellm_params:
      model: "huggingface/meta-llama/Llama-2-7b"
      api_base: "http://host.docker.internal:8080"
      max_tokens: 2048

litellm_settings:
  set_verbose: True
  cache: True
  cache_params:
    type: "redis"