version: "3.4"

services:
  redis:
    image: redis/redis-stack:latest
    environment:
      - "REDIS_ARGS=--save 10 1 --appendonly yes"
    volumes:
      - $HOME/.cache/litellm/redis-data:/data
    ports:
      - "6379:6379"
      - "13001:8001"
  litellm-proxy:
    depends_on:
      - redis
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "8111:8111"
    volumes:
      - ./config.yaml:/app/config.yaml
    command: [ "--config", "/app/config.yaml", "--port", "8111", "--num_workers", "1" ]
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}"
      - "OPENAI_API_KEY=${OPENAI_API_KEY}"
      - "GROQ_API_KEY=${GROQ_API_KEY}"
      - "TOGETHERAI_API_KEY=${TOGETHERAI_API_KEY}"
      - "HF_TOKEN=${HF_TOKEN}"
    extra_hosts:
      - "host.docker.internal:host-gateway"