stages:
  answer-questions:
    cmd: >-
      python answer_questions.py
      --dataset-path ${dataset.path}
      --dataset-name ${dataset.name}
      --dataset-split ${dataset.split}
      --out ../../data/generated/research-mhqa-evaluation/qa-results/
      --prompt ${qa.prompt}
      --model ${qa.model}
      --temperature ${qa.temperature}
    deps:
      - answer_questions.py
    outs:
      - ../../data/generated/research-mhqa-evaluation/qa-results/
    params:
      - dataset.path
      - dataset.name
      - dataset.split
      - qa.prompt
      - qa.model
      - qa.temperature
      - run
  
  evaluate-answers:
    cmd: >-
      python evaluate_answers.py
      --dataset-path ${dataset.path}
      --dataset-name ${dataset.name}
      --dataset-split ${dataset.split}
      --qa-dir ../../data/generated/research-mhqa-evaluation/qa-results/
      --out ../../data/generated/research-mhqa-evaluation/evals/
    deps:
      - evaluate_answers.py
      - ../../data/generated/research-mhqa-evaluation/qa-results/
    outs:
      - ../../data/generated/research-mhqa-evaluation/evals/
    params:
      - dataset.path
      - dataset.name
      - dataset.split

  report:
    cmd: >-
      python report.py
      --dataset-path ${dataset.path}
      --dataset-name ${dataset.name}
      --dataset-split ${dataset.split}
      --qa-dir ../../data/generated/research-mhqa-evaluation/qa-results/
      --evals-dir ../../data/generated/research-mhqa-evaluation/evals/
      --out ../../data/generated/research-mhqa-evaluation/reports/
    deps:
      - report.py
      - ../../data/generated/research-mhqa-evaluation/qa-results/
      - ../../data/generated/research-mhqa-evaluation/evals/
    outs:
      - ../../data/generated/research-mhqa-evaluation/reports/results.jsonl
    metrics:
      - ../../data/generated/research-mhqa-evaluation/reports/scores.json
    params:
      - dataset.path
      - dataset.name
      - dataset.split