dataset:
  path: bdsaglam/musique-mini
  name: answerable
  split: train
qa:
  model: llama-3-70b-tgi
  temperature: 0.1
  system_prompt: no-role-cte.txt
  user_prompt_template: cq.txt
  few_shot_examples: empty.json
run: 2
