stages:
  create_mhqa_dataset:
    wdir: ../..
    cmd: >-
      python pipelines/musique-kg-llm/create_mhqa_dataset.py
      --config-file data/raw/musique-kg-llm/train/dataset-config.json
      --out data/generated/musique-kg-llm/train/dataset.jsonl
    deps:
      - pipelines/musique-kg-llm/create_mhqa_dataset.py
      - data/raw/musique-kg-llm/train/dataset-config.json
    outs:
      - data/generated/musique-kg-llm/train/dataset.jsonl

  decompose_questions:
    wdir: ../..
    cmd: >-
      python pipelines/musique-kg-llm/decompose_questions.py
      --dataset-file data/generated/musique-kg-llm/train/dataset.jsonl
      --out data/generated/musique-kg-llm/train/question-decomposition.jsonl
    deps:
      - pipelines/musique-kg-llm/decompose_questions.py
      - data/generated/musique-kg-llm/train/dataset.jsonl
    outs:
      - data/generated/musique-kg-llm/train/question-decomposition.jsonl

  construct_knowledge_graphs:
    frozen: true
    wdir: ../..
    cmd: >-
      python pipelines/musique-kg-llm/construct_knowledge_graphs.py
      --dataset-file data/generated/musique-kg-llm/train/dataset.jsonl
      --llm-config-file data/raw/musique-kg-llm/train/erx-llm-configs/llama2-sft.json
      --out data/generated/musique-kg-llm/train/knowledge-graphs/
    deps:
      - pipelines/musique-kg-llm/construct_knowledge_graphs.py
      - data/generated/musique-kg-llm/train/dataset.jsonl
    outs:
      - data/generated/musique-kg-llm/train/knowledge-graphs/timestamp.txt

  answer_questions:
    frozen: true
    wdir: ../..
    cmd: >-
      python pipelines/musique-kg-llm/answer_questions.py
      --dataset-file data/generated/musique-kg-llm/train/question-decomposition.jsonl
      --knowledge-graph-directory data/generated/musique-kg-llm/train/knowledge-graphs/ 
      --out data/generated/musique-kg-llm/train/answers.jsonl
    deps:
      - pipelines/musique-kg-llm/answer_questions.py
      - data/generated/musique-kg-llm/train/question-decomposition.jsonl
      - data/generated/musique-kg-llm/train/knowledge-graphs/timestamp.txt
    outs:
      - data/generated/musique-kg-llm/train/answers.jsonl

  evaluate_answers:
    frozen: true
    wdir: ../..
    cmd: >-
      python pipelines/musique-kg-llm/evaluate_answers.py
      --dataset-file data/generated/musique-kg-llm/train/dataset.jsonl
      --answers-file data/generated/musique-kg-llm/train/answers.jsonl
      --out data/generated/musique-kg-llm/train/answer-eval/
    deps:
      - pipelines/musique-kg-llm/evaluate_answers.py
      - data/generated/musique-kg-llm/train/dataset.jsonl
      - data/generated/musique-kg-llm/train/answers.jsonl
    outs:
      - data/generated/musique-kg-llm/train/answer-eval/comparisons.jsonl
      - data/generated/musique-kg-llm/train/answer-eval/scores.json

  prepare_jerx_reward_dataset:
    wdir: ../..
    cmd: >-
      python pipelines/musique-kg-llm/prepare_jerx_reward_dataset.py
      --knowledge-graph-directory data/generated/musique-kg-llm/train/knowledge-graphs/
      --answer-comparisons-file data/generated/musique-kg-llm/train/answer-eval/comparisons.jsonl
      --out data/generated/musique-kg-llm/train/jerx-reward-dataset.jsonl
    deps:
      - pipelines/musique-kg-llm/prepare_jerx_reward_dataset.py
      - data/generated/musique-kg-llm/train/knowledge-graphs/
      - data/generated/musique-kg-llm/train/answer-eval/comparisons.jsonl
    outs:
      - data/generated/musique-kg-llm/train/jerx-reward-dataset.jsonl

  publish_jerx_reward_modelling_datasets:
    wdir: ../..
    cmd: >-
      python pipelines/musique-kg-llm/publish_jerx_reward_modelling_datasets.py
      --reward-dataset-path data/generated/musique-kg-llm/train/jerx-reward-dataset.jsonl
      --out data/generated/musique-kg-llm/train/jerx-reward-datasets-info.txt
    deps:
      - pipelines/musique-kg-llm/publish_jerx_reward_modelling_datasets.py
      - data/generated/musique-kg-llm/train/jerx-reward-dataset.jsonl
    outs:
      - data/generated/musique-kg-llm/train/jerx-reward-datasets-info.txt
