stages:
  create_mini_dataset:
    wdir: ../..
    cmd: >-
      head -n 1000 data/generated/musique-common/base-dataset-train.jsonl > data/generated/musique-training/dataset.jsonl
    deps:
      - data/generated/musique-common/base-dataset-train.jsonl
    outs:
      - data/generated/musique-training/dataset.jsonl

  decompose_questions:
    wdir: ../..
    cmd: >-
      python pipelines/musique-common/decompose_questions.py
      --dataset-file data/generated/musique-training/dataset.jsonl
      --out data/generated/musique-training/question-decomposition.jsonl
    deps:
      - pipelines/musique-common/decompose_questions.py
      - data/generated/musique-training/dataset.jsonl
    outs:
      - data/generated/musique-training/question-decomposition.jsonl

  construct_knowledge_graphs:
    wdir: ../..
    cmd: >-
      python pipelines/musique-common/construct_knowledge_graphs.py
      --dataset-file data/generated/musique-training/dataset.jsonl
      --llm-config-file data/raw/musique-training/jerx-llm-configs/llama3.json
      --out data/generated/musique-training/knowledge-graphs/
    deps:
      - pipelines/musique-common/construct_knowledge_graphs.py
      - data/raw/musique-training/jerx-llm-configs/llama3.json
      - data/generated/musique-training/dataset.jsonl
    outs:
      - data/generated/musique-training/knowledge-graphs/timestamp.txt

  answer_questions:
    wdir: ../..
    cmd: >-
      python pipelines/musique-common/answer_questions.py
      --dataset-file data/generated/musique-training/question-decomposition.jsonl
      --knowledge-graph-directory data/generated/musique-training/knowledge-graphs/ 
      --out data/generated/musique-training/question-answering
    deps:
      - pipelines/musique-common/answer_questions.py
      - data/generated/musique-training/question-decomposition.jsonl
      - data/generated/musique-training/knowledge-graphs/timestamp.txt
    outs:
      - data/generated/musique-training/question-answering/timestamp.txt

  evaluate_answers:
    wdir: ../..
    cmd: >-
      python pipelines/musique-common/evaluate_answers.py
      --dataset-file data/generated/musique-training/dataset.jsonl
      --answers-dir data/generated/musique-training/question-answering/
      --out data/generated/musique-training/answer-eval/
    deps:
      - pipelines/musique-common/evaluate_answers.py
      - data/generated/musique-training/dataset.jsonl
      - data/generated/musique-training/question-answering/
    outs:
      - data/generated/musique-training/answer-eval/comparisons.jsonl
      - data/generated/musique-training/answer-eval/scores.json

  create_jerx_sft_dataset:
    wdir: ../..
    cmd: >-
      python pipelines/musique-training/create_jerx_sft_datasetv.py
      --dataset-file data/generated/musique-training/dataset.jsonl
      --answer-comparison-file data/generated/musique-training/answer-eval/comparisons.jsonl
      --out data/generated/musique-training/jerx/
    deps:
      - pipelines/musique-common/evaluate_answers.py
      - data/generated/musique-training/dataset.jsonl
      - data/generated/musique-training/answer-eval/comparisons.jsonl
    outs:
      - data/generated/musique-training/jerx/jerx-chat.jsonl
