stages:
  create_mini_dataset:
    wdir: ../..
    cmd: >-
      head -n 100 data/generated/musique-common/base-dataset-validation.jsonl > data/generated/musique-evaluation/dataset.jsonl
    deps:
      - data/generated/musique-common/base-dataset-validation.jsonl
    outs:
      - data/generated/musique-evaluation/dataset.jsonl

  decompose_questions:
    wdir: ../..
    cmd: >-
      python pipelines/musique-common/decompose_questions.py
      --dataset-file data/generated/musique-evaluation/dataset.jsonl
      --out data/generated/musique-evaluation/question-decomposition.jsonl
    deps:
      - pipelines/musique-common/decompose_questions.py
      - data/generated/musique-evaluation/dataset.jsonl
    outs:
      - data/generated/musique-evaluation/question-decomposition.jsonl

  construct_knowledge_graphs:
    wdir: ../..
    cmd: >-
      python pipelines/musique-common/construct_knowledge_graphs.py
      --dataset-file data/generated/musique-evaluation/dataset.jsonl
      --llm-config-file data/raw/musique-evaluation/jerx-llm-configs/llama3-base-offline.json
      --out data/generated/musique-evaluation/knowledge-graphs/
    deps:
      - pipelines/musique-common/construct_knowledge_graphs.py
      - data/raw/musique-evaluation/jerx-llm-configs/llama3-base-offline.json
      - data/generated/musique-evaluation/dataset.jsonl
    outs:
      - data/generated/musique-evaluation/knowledge-graphs/timestamp.txt

  answer_questions:
    wdir: ../..
    cmd: >-
      python pipelines/musique-common/answer_questions.py
      --dataset-file data/generated/musique-evaluation/question-decomposition.jsonl
      --knowledge-graph-directory data/generated/musique-evaluation/knowledge-graphs/ 
      --out data/generated/musique-evaluation/question-answering
    deps:
      - pipelines/musique-common/answer_questions.py
      - data/generated/musique-evaluation/question-decomposition.jsonl
      - data/generated/musique-evaluation/knowledge-graphs/timestamp.txt
    outs:
      - data/generated/musique-evaluation/question-answering/timestamp.txt

  evaluate_answers:
    wdir: ../..
    cmd: >-
      python pipelines/musique-common/evaluate_answers.py
      --dataset-file data/generated/musique-evaluation/dataset.jsonl
      --answers-dir data/generated/musique-evaluation/question-answering/
      --out data/generated/musique-evaluation/answer-eval/
    deps:
      - pipelines/musique-common/evaluate_answers.py
      - data/generated/musique-evaluation/dataset.jsonl
      - data/generated/musique-evaluation/question-answering/
    outs:
      - data/generated/musique-evaluation/answer-eval/comparisons.jsonl
      - data/generated/musique-evaluation/answer-eval/scores.json
